### ISSUE TITLE
Fails on gitbook.com and Ubuntu

### ISSUE THREAD

**Issue by hamishwillee** [Popog/gitbook-plugin-validate-links#1]
This works on Windows, but on Ubuntu I get the following error:

```
info: loading plugin "validate-links"... ERROR

PluginError: Error with plugin "validate-links": Unexpected token {
ubuntu@ubuntu:~/github/forks/minimal_gitbook_test$ 
```

If plugin is in book.json, the book will also not build on gitbook.com

**Comment by noerw** [comment]
it works for me on ubuntu with node `v6.10.2`
i suppose its an issue with the node version, as gitbook seems to deploy node `v4.x`

**Comment by noerw** [comment]
it must be the arrow functions: https://github.com/Popog/gitbook-plugin-validate-links/blob/master/index.js#L24

@hamishwillee can you run `gitbook -d build` locally? this will output the erroring line number

**Comment by hamishwillee** [comment]
Hi,
The output is:
```
ubuntu@ubuntu:~/github/forks/minimal_gitbook_test$ gitbook -d build
info: parsing multilingual book, with 2 languages 
info: 17 plugins are installed 
info: 16 explicitly listed 
info: loading plugin "youtube"... OK 
info: loading plugin "richquotes"... OK 
info: loading plugin "language-picker"... OK 
info: loading plugin "collapsible-menu"... OK 
info: loading plugin "page-toc-button"... OK 
info: loading plugin "page-footer-ex"... OK 
info: loading plugin "custom-favicon"... OK 
info: loading plugin "toolbar"... OK 
info: loading plugin "redirect-root"... OK 
info: loading plugin "validate-links"... ERROR

PluginError: Error with plugin "validate-links": Unexpected token {
PluginError: Error with plugin "validate-links": Unexpected token {
    at createError (/home/ubuntu/.gitbook/versions/3.2.2/node_modules/error/typed.js:31:22)
    at new createError (/home/ubuntu/.gitbook/versions/3.2.2/node_modules/error/wrapped.js:88:19)
    at /home/ubuntu/.gitbook/versions/3.2.2/lib/plugins/loadPlugin.js:67:23
    at _fulfilled (/home/ubuntu/.gitbook/versions/3.2.2/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/ubuntu/.gitbook/versions/3.2.2/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/ubuntu/.gitbook/versions/3.2.2/node_modules/q/q.js:796:13)
    at /home/ubuntu/.gitbook/versions/3.2.2/node_modules/q/q.js:857:14
    at runSingle (/home/ubuntu/.gitbook/versions/3.2.2/node_modules/q/q.js:137:13)
    at flush (/home/ubuntu/.gitbook/versions/3.2.2/node_modules/q/q.js:125:13)
    at nextTickCallbackWith0Args (node.js:419:9)
```

This is node 4.2.6

**Comment by hamishwillee** [comment]
Awesome. Any thoughts when a new version will be released on npm?

**Comment by Popog** [comment]
Should be up now.

**Comment by hamishwillee** [comment]
Thanks. It works :-)
